server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    # #表示向注册中心注册自己
    register-with-eureka: true
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: true
    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://localhost:7001/eureka